version: "3.7"
services:
  fog-node:
    build: .
    command: /bin/sh -c "sleep 10 && npx sequelize-cli db:migrate && npm start"
    environment:
      DB_HOST: pg
      PORT: 4000
    networks:
      - fn
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fn
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  db_data:

networks:
  fn:
    name: fn